name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  combine-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: Nanook/GrindCore.build
          token: ${{ secrets.BUILD_READ }}
          path: build

      - name: Combine filesystems
        run: |
          ls -al
          rsync -a external/ build/src/native/external/
          rsync -a libs/ build/src/native/libs/
          rsync -a minipal/ build/src/native/minipal/
          rm -rf build/.github
          rm -rf build/.git
          mv build/* .

      - name: Upload combined filesystem
        uses: actions/upload-artifact@v3
        with:
          name: combined-filesystem
          path: .

  # call-reusable-workflow:
  #   needs: combine-and-build
  #   uses: Nanook/GrindCore.build/.github/workflows/ci.yaml@main
  #   secrets:
  #     GRINDCORE_BUILD_READ: ${{ secrets.BUILD_READ }}
